# Port ranges (by convention):
#  - API: 3000-3999
#  - Services: 4000-4999
#  - Mocks: 5000-5999
#  - Documentation: 7000-7999
#  - Websites: 9000-9999
#
# Please run `make install` to get the dependencies install

version: "3.7"
services:
    front-end-app:
        image: node:14-alpine
        environment:
          # please override this locally if using not using localhost or ip address to browse the site in dev.
          SUBDOMAIN_OFFSET: 0
          USE_SECURE_SESSION_COOKIES: "false"
        ports:
          - 9000:3000
          # node debugger
          # - 9229:9229
        working_dir: /opt/app
        volumes:
          - ./packages/front-end-app:/opt/app
        restart: unless-stopped
        command: npm run start:docker:dev
        # if enabling debug, be sure to uncomment / expose the debug port above.
        # command: npm run start:dev:debug